# Generated by Django 5.1.3 on 2025-04-10 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sat_track', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccountModel',
        ),
    ]
