# Generated by Django 5.2 on 2026-03-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sat_track", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="satellite_key",
            field=models.CharField(default="sentinel-2a", max_length=30),
        ),
    ]
