# Generated by Django 5.1.3 on 2025-04-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sat_track', '0002_delete_useraccountmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccountModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=65)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
