# Generated by Django 5.2 on 2025-04-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat_track', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('area_geojson', models.JSONField()),
            ],
        ),
    ]
