# Generated by Django 5.1.7 on 2025-04-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sat_track', '0004_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='area_geojson',
            field=models.TextField(),
        ),
    ]
